<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../api'

const tab = ref('departments'), saved = ref(false), notice = ref(''), error = ref('')
const departmentModal = ref(false), inviteModal = ref(false), roleModal = ref(false), roleEditor = ref(null)
const departmentDraft = ref({ name: '', parent_id: '' }), inviteDraft = ref({ username: '', password: '', department_id: '', role_id: '' }), roleDraft = ref({ name: '', code: '' })
const departments = ref([{name:'总部', code:'HQ', id:'', children:[{name:'研发部', code:'RD', id:'', members:0}]}])
const users = ref([]), roles = ref([])
const permissionOptions = ['organization.read','organization.admin','knowledge.read','knowledge.write','knowledge.admin','chat.use','faq.review','audit.read']
const flatDepartments = computed(() => departments.value.flatMap(root => [{ id: root.id, name: root.name }, ...(root.children || []).map(child => ({ id: child.id, name: child.name }))]))
async function load(){ try { const [dept, user, role] = await Promise.all([api('/api/organization/departments'), api('/api/organization/users'), api('/api/organization/roles')]); if(dept.length) { const roots=dept.filter(x=>!x.parent_id); departments.value=roots.map(root=>({ ...root, code:root.id.slice(-2).toUpperCase(), children:dept.filter(x=>x.parent_id===root.id).map(x=>({...x,code:x.id.slice(-2).toUpperCase(),members:user.filter(u=>u.department_id===x.id).length})) })) } if(user.length) users.value=user; if(role.length) roles.value=role } catch(e) { error.value=e.message } }
async function createDepartment(){ try { const result=await api('/api/organization/departments',{method:'POST',body:JSON.stringify(departmentDraft.value)}); notice.value=`部门「${result.name}」已创建`; departmentModal.value=false; departmentDraft.value={name:'',parent_id:''}; await load() } catch(e){ error.value=e.message } }
async function inviteUser(){ try { await api('/api/organization/users',{method:'POST',body:JSON.stringify(inviteDraft.value)}); notice.value='用户已创建并绑定到单一部门'; inviteModal.value=false; inviteDraft.value={username:'',password:'',department_id:'',role_id:''}; await load() } catch(e){ error.value=e.message } }
async function createRole(){ try { await api('/api/organization/roles',{method:'POST',body:JSON.stringify(roleDraft.value)}); notice.value='角色已创建'; roleModal.value=false; roleDraft.value={name:'',code:''}; await load() } catch(e){ error.value=e.message } }
async function toggleUser(user){ try { await api(`/api/organization/users/${user.id}`,{method:'PATCH',body:JSON.stringify({active:user.active})}); notice.value=`账号 ${user.username} 状态已更新` } catch(e){ user.active=!user.active; error.value=e.message } }
async function saveRole(role){ try { await api(`/api/organization/roles/${role.id}/permissions`,{method:'PUT',body:JSON.stringify({permissions:role.permissions})}); roleEditor.value=null; notice.value=`${role.name} 权限已保存` } catch(e){ error.value=e.message } }
function save(){saved.value=true;setTimeout(()=>saved.value=false,2000)}
onMounted(load)
</script>

<template>
  <section class="organization-page"><div class="title-row"><div><div class="eyebrow">ORGANIZATION & SETTINGS</div><h1>组织架构与系统配置</h1><p>管理部门范围、角色权限和底层模型接口。</p></div><button @click="save">保存配置</button></div><p v-if="saved" class="notice">配置已保存</p><p v-if="notice" class="notice">{{notice}}</p><p v-if="error" class="error">{{error}}</p>
    <div class="tab-bar card org-tabs"><button :class="{active:tab==='departments'}" @click="tab='departments'">部门架构</button><button :class="{active:tab==='users'}" @click="tab='users'">用户账号</button><button :class="{active:tab==='roles'}" @click="tab='roles'">角色权限</button><button :class="{active:tab==='models'}" @click="tab='models'">模型接口</button></div>
    <article v-if="tab==='departments'" class="card settings-panel"><div class="panel-heading"><div><b>部门树形结构</b><small>部门权限默认覆盖下级，用户只能归属一个部门</small></div><button class="secondary" @click="departmentModal=true">+ 新增部门</button></div><div class="tree"><div v-for="root in departments" :key="root.id || root.code" class="tree-root"><span class="tree-caret">⌄</span><span class="folder">▰</span><b>{{root.name}}</b><small>{{root.code}}</small><div v-for="child in root.children" :key="child.id || child.code" class="tree-child"><span class="tree-line"></span><span class="folder light">▰</span><b>{{child.name}}</b><small>{{child.code}} · {{child.members || 0}} 人</small></div></div></div></article>
    <article v-else-if="tab==='users'" class="card settings-panel"><div class="panel-heading"><div><b>用户账号状态</b><small>支持停用、转移部门和调整角色</small></div><button class="secondary" @click="inviteModal=true">+ 邀请用户</button></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>所属部门</th><th>角色</th><th>账号状态</th><th></th></tr></thead><tbody><tr v-for="user in users" :key="user.id || user.username"><td><div class="user-cell"><span class="avatar">{{user.username.slice(0,1).toUpperCase()}}</span><div><b>{{user.username}}</b><small>{{user.id}}</small></div></div></td><td>{{user.department}}</td><td><span class="role-chip">{{user.role}}</span></td><td><label class="switch-label compact"><input v-model="user.active" type="checkbox" @change="toggleUser(user)"><i></i><span>{{user.active?'正常':'已停用'}}</span></label></td><td><button class="text-button" @click="notice='用户编辑请修改部门或状态后保存'">编辑</button></td></tr></tbody></table><div v-if="!users.length" class="empty compact-empty">暂无用户数据</div></div></article>
    <article v-else-if="tab==='roles'" class="card settings-panel"><div class="panel-heading"><div><b>角色功能操作权限树</b><small>管理员可将权限赋予角色，权限变更会立即记录审计日志</small></div><button class="secondary" @click="roleModal=true">+ 新建角色</button></div><div class="role-list"><div v-for="role in roles" :key="role.id || role.name" class="role-card"><div class="role-card-head"><div><b>{{role.name}}</b><small>{{role.code}}</small></div><button class="text-button" @click="roleEditor=role">编辑权限</button></div><div v-if="roleEditor===role" class="permission-editor"><label v-for="permission in permissionOptions" :key="permission"><input v-model="role.permissions" type="checkbox" :value="permission">{{permission}}</label><button class="secondary" @click="saveRole(role)">保存权限</button></div><div v-else class="permission-chips"><span v-for="permission in role.permissions" :key="permission" class="permission-chip"><i>✓</i>{{permission}}</span></div></div></div></article>
    <article v-else class="card settings-panel"><div class="panel-heading"><div><b>底层模型接口配置</b><small>密钥仅存储在服务器环境变量，前端不展示</small></div><span class="connected"><i></i>连接正常</span></div><div class="model-grid"><label>Chat 模型<input value="deepseek-ai/DeepSeek-V3" readonly><small>硅基流动 · 用于问答与文档分析</small></label><label>Embedding 模型<input value="BAAI/bge-large-zh-v1.5" readonly><small>向量维度 1024 · Milvus</small></label><label>Rerank 模型<input value="BAAI/bge-reranker-v2-m3" readonly><small>用于候选证据重排</small></label><label>MCP 服务<input value="百炼 WebSearch MCP" readonly><small>三路检索中的联网搜索通道</small></label></div></article>
    <div v-if="departmentModal || inviteModal || roleModal" class="overlay" @click.self="departmentModal=false;inviteModal=false;roleModal=false"><div class="modal card faq-editor"><div class="drawer-head"><b>{{departmentModal?'新增部门':inviteModal?'邀请用户':'新建角色'}}</b><button class="icon-button" @click="departmentModal=false;inviteModal=false;roleModal=false">×</button></div><div v-if="departmentModal"><label>部门名称<input v-model="departmentDraft.name"></label><label>上级部门<select v-model="departmentDraft.parent_id"><option value="">无（顶级部门）</option><option v-for="item in flatDepartments" :key="item.id" :value="item.id">{{item.name}}</option></select></label><button @click="createDepartment">创建部门</button></div><div v-else-if="inviteModal"><label>账号<input v-model="inviteDraft.username"></label><label>初始密码<input v-model="inviteDraft.password" type="password"></label><label>所属部门<select v-model="inviteDraft.department_id"><option v-for="item in flatDepartments" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label>角色<select v-model="inviteDraft.role_id"><option v-for="role in roles" :key="role.id" :value="role.id">{{role.name}}</option></select></label><button @click="inviteUser">创建用户</button></div><div v-else><label>角色名称<input v-model="roleDraft.name"></label><label>角色编码<input v-model="roleDraft.code"></label><button @click="createRole">创建角色</button></div></div></div>
  </section>
</template>
